name: QA Wolf Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        record: ["record", "no-record"]
        browser: ["chromium", "firefox"]
    env:
      RECORD_REPLAY_API_KEY: rwk_dkcLU5trLw9tvbbNukNj0xRVl65iVBj2E0qlnz8TL6v

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install Replay Browsers
        run: npx @replayio/playwright install

      - name: Generate Test Run ID
        id: test-run-id
        run: echo "::set-output name=uuid::$(npx uuid)"

      - name: Run Tests
        run: RECORD_REPLAY_NO_RECORD=${{ matrix.record == 'no-record' && '1' || '' }} PLAYWRIGHT_CHROMIUM=${{ matrix.browser == 'chromium' && '1' || ''}} node ./qawolf-tests.js
        env:
          TEST_RUN_ID: ${{ steps.test-run-id.outputs.uuid }}
          RECORD_REPLAY_HEADLESS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}

      - name: Upload Replays
        uses: replayio/action-upload@v0.4.3
        if: always()
        with:
          api-key: ${{ env.RECORD_REPLAY_API_KEY }}
          public: true
